### ISSUE TITLE
I could only manage to have the function on my path one time

### ISSUE THREAD

**Issue by i-am-the-slime** [lilyball/nix-env.fish#2]
And that was the first time I installed this. I can't get `nix-shell` or anything like that to run.
I installed exactly as outlined in the README. I wonder if I need to fiddle with some `PATH`.

**Comment by lilyball** [comment]
I apologize for the late response, it seems I never got an email about this.

Are you using a single-user or a multi-user install? This plugin was designed for single-user as I don't have a non-NixOS multi-user install to test with. #1 is an open PR to fix this, if you're using a multi-user install.

**Comment by lilyball** [comment]
Multi-user install should work now. Please let me know if you continue to have an issue.

**Comment by lilyball** [comment]
Closing this issue as stale. Please file a new issue if you still have this problem.
