### ISSUE TITLE
Multi User detection fails if ls is an alias

### ISSUE THREAD

**Issue by Memphizzz** [lilyball/nix-env.fish#9]
Hi there,

first of all, thank you very much for this great solution for running nix with fish.
I just came accross a little problem when installing through fisher on a multi-user environment.
In my case `ls` is an alias for `exa` which leads to line 26 not being able to detect whether or not `/nix/store` is owned by root.
A quick fix was to simply change `ls` to `/bin/ls` in my case.

Maybe you could add that for the future?

Have a nice day!

**Comment by lilyball** [comment]
Probably a good idea. In the meantime I might suggest changing the alias into an [abbreviation](https://fishshell.com/docs/current/cmds/abbr.html) instead, so using `ls` at the command-line will replace it automatically with `exa` but any scripts invoking `ls` directly won't be affected. That's what I've been doing, though using `lx` as my abbreviation so I can easily invoke `ls` as needed.

**Comment by Memphizzz** [comment]
I checked abbreviations out, my problem with them is that if you have a long alias like `ls 'ls -lah --color=always --group-directories-first'` and you do arrow-up it will show you the abbreviated command instead of the abbreviation itself, which is ugly. Hence I still prefer aliases. As for the ls problem above, instead of using `/bin/ls`, `command ls` would also do the trick which seems to be the intended way of making sure not to use an alias but the real command.

**Comment by howardburgess** [comment]
Fixed by https://github.com/lilyball/nix-env.fish/pull/10?

**Comment by lilyball** [comment]
I suspect you're right. I'm going to close this, please let me know if there's still an issue.
